FROM node:20.11.1-alpine

RUN apk update
RUN apk upgrade
RUN apk add git

WORKDIR /app
ADD package.json package-lock.json ./
RUN npm i nodemon ts-node @nestjs/cli -g
RUN npm ci
ADD . /app

ENTRYPOINT ["npm", "run", "start:dev"]