version: "1.0"

services:
  # backend:
    # container_name: dgs_backend
    # build:
    #   context: ../../services/backend
    #   dockerfile: Dockerfile.dev
    # restart: always
    # volumes:
    #   - "../../services/backend:/app"
    # environment:
    #   - BACKEND_PORT=${BACKEND_PORT}
    #   - POSTGRES_HOST=${POSTGRES_HOST}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_PORT=${POSTGRES_PORT}
    # ports:
    #   - ${BACKEND_PORT}:${BACKEND_PORT}
    # networks:
    #   - network-name
    
  postgres:
    image: postgres:latest
    container_name: dgs_db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network-name

volumes:
  postgres_data:
networks:
  network-name:
    driver: bridge
  